-- Bindit schema for Supabase Postgres.
-- Run this in the Supabase SQL Editor (Project → SQL Editor → New query).
-- The FastAPI backend uses the database password (postgres role), which
-- bypasses Row Level Security. RLS is enabled with no public policies so
-- the Supabase REST/anon keys cannot read or write learner data.

create table if not exists student_progress (
  student_id text primary key,
  total_xp integer not null default 0,
  attempts integer not null default 0,
  correct_answers integer not null default 0,
  streak integer not null default 0,
  best_streak integer not null default 0,
  last_active_date date,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists topic_progress (
  student_id text not null references student_progress(student_id) on delete cascade,
  topic text not null,
  attempts integer not null default 0,
  correct_answers integer not null default 0,
  primary key (student_id, topic)
);

create table if not exists profiles (
  student_id text primary key references student_progress(student_id) on delete cascade,
  username varchar(24) not null unique,
  display_name varchar(40) not null,
  friend_code varchar(12) not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists friendships (
  id integer generated by default as identity primary key,
  requester_id varchar(100) not null references profiles(student_id) on delete cascade,
  recipient_id varchar(100) not null references profiles(student_id) on delete cascade,
  status varchar(10) not null default 'pending',
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_friend_request_direction unique (requester_id, recipient_id)
);

create table if not exists uploaded_images (
  id uuid primary key,
  owner_id text not null,
  storage_path text not null unique,
  original_name varchar(255) not null,
  content_type varchar(100) not null,
  size_bytes integer not null check (size_bytes > 0 and size_bytes <= 5242880),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists topic_progress_student_id_idx
  on topic_progress (student_id);

create index if not exists uploaded_images_owner_id_idx
  on uploaded_images (owner_id, created_at desc);

alter table student_progress enable row level security;
alter table topic_progress enable row level security;
alter table profiles enable row level security;
alter table friendships enable row level security;
alter table uploaded_images enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'student-images',
  'student-images',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Intentionally no policies for anon/authenticated.
-- Backend access uses DATABASE_URL (postgres role), not the anon key.
