-- Phase 1: accounts, profiles, guest claims, login streaks, secure quiz questions, and private uploads.
-- Safe to run on an existing bindit database.

alter table student_progress add column if not exists login_streak integer not null default 0;
alter table student_progress add column if not exists best_login_streak integer not null default 0;
alter table student_progress add column if not exists last_login_date date;

create table if not exists profiles (
  student_id text primary key references student_progress(student_id) on delete cascade,
  username varchar(24) not null unique,
  display_name varchar(40) not null,
  avatar_path varchar(500) not null default '',
  friend_code varchar(12) not null unique,
  daily_goal integer not null default 20,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table profiles add column if not exists avatar_path varchar(500) not null default '';
alter table profiles add column if not exists daily_goal integer not null default 20;
alter table profiles add column if not exists updated_at timestamptz not null default timezone('utc', now());

create table if not exists progress_claims (
  guest_id text primary key,
  account_id text not null,
  claimed_at timestamptz not null default timezone('utc', now())
);

create table if not exists generated_questions (
  question_id varchar(64) primary key,
  student_id varchar(100) not null,
  question varchar(500) not null,
  correct_answer varchar(200) not null,
  topic varchar(50) not null,
  difficulty integer not null,
  completed integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists friendships (
  id integer generated by default as identity primary key,
  requester_id varchar(100) not null references profiles(student_id) on delete cascade,
  recipient_id varchar(100) not null references profiles(student_id) on delete cascade,
  status varchar(10) not null default 'pending',
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_friend_request_direction unique (requester_id, recipient_id)
);

create table if not exists uploaded_images (
  id uuid primary key,
  owner_id text not null,
  storage_path text not null unique,
  original_name varchar(255) not null,
  content_type varchar(100) not null,
  size_bytes integer not null check (size_bytes > 0 and size_bytes <= 5242880),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists progress_claims_account_id_idx on progress_claims (account_id);
create index if not exists profiles_username_idx on profiles (username);
create index if not exists generated_questions_student_id_idx on generated_questions (student_id);
create index if not exists uploaded_images_owner_id_idx on uploaded_images (owner_id, created_at desc);

alter table student_progress enable row level security;
alter table topic_progress enable row level security;
alter table profiles enable row level security;
alter table progress_claims enable row level security;
alter table generated_questions enable row level security;
alter table friendships enable row level security;
alter table uploaded_images enable row level security;

-- Intentionally no anon/authenticated policies. The backend uses DATABASE_URL.
