create table if not exists friend_quests (
  id integer generated by default as identity primary key,
  creator_id varchar(100) not null references profiles(student_id) on delete cascade,
  partner_id varchar(100) not null references profiles(student_id) on delete cascade,
  target_xp integer not null default 100 check (target_xp between 50 and 1000),
  starting_xp integer not null default 0,
  status varchar(12) not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null
);

create index if not exists friend_quests_members_idx
  on friend_quests (creator_id, partner_id, status, expires_at desc);

alter table friend_quests enable row level security;
